#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
sxhkd -c ~/.config/sxhkd/sxhkdrc &
xrandr --output eDP1 --mode 1920x1080 --rate 60
bspc monitor -d 1 2 3 4 5 6 7

bspc config border_width         2
bspc config window_gap          25

bspc config split_ratio          0.60
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#AutoStart applications
sxhkd &
picom --config ~/.config/picom/picom.conf &
feh --bg-scale ~/Wallpapers/wallpaper.png &
dunst &
polybar &
